[paths]
scripts = "./scripts"
logs = "./logs"

[ui]
theme = "tokyo-night"

[scripts]
timeout = 3

# Health Checker - Services locations
# In order to add a new service, use the following structure:
# [[services]]
# name = "service 1"
# server = "localhost"
# environment = "PROD"

[[services]]
name = "My Test Service 1"
server = "localhost"
environment = "dev"

[[services]]
name = "My Test Service 2"
server = "localhost"
environment = "dev"