[project]
name = "toolbox"
version = "0.1.0"
description = "TUI to centralize scripts I run on a daily basis."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyperclip>=1.11.0",
    "rich>=15.0.0",
    "textual[syntax]>=8.2.7",
    "tomlkit>=0.15.1",
    "tree-sitter-bash>=0.25.1",
    "tree-sitter-c>=0.24.2",
    "tree-sitter-cpp>=0.23.4",
    "tree-sitter-go>=0.25.0",
    "tree-sitter-java>=0.23.5",
    "tree-sitter-javascript>=0.25.0",
    "tree-sitter-lua>=0.5.0",
    "tree-sitter-powershell>=0.26.4",
    "tree-sitter-pwsh>=0.38.1",
    "tree-sitter-python>=0.25.0",
    "tree-sitter-ruby>=0.23.1",
    "tree-sitter-rust>=0.24.2",
    "tree-sitter-sql>=0.3.11",
    "tree-sitter-typescript>=0.23.2",
    "tree-sitter-yaml>=0.7.2",
]

[project.scripts]
toolboxtui = "main:main"
